# Generated by Django 2.2 on 2019-04-09 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remision',
            name='entrego',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empleado.Empleado'),
            preserve_default=False,
        ),
    ]
