# Generated by Django 2.2 on 2019-05-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remision', '0002_auto_20190409_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remision',
            old_name='Guia',
            new_name='guia',
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='remision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='remision.Remision'),
        ),
    ]
