# Generated by Django 2.2 on 2019-05-29 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remision', '0005_auto_20190529_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remision',
            name='estado',
        ),
        migrations.DeleteModel(
            name='EstadoRemision',
        ),
    ]
