# Generated by Django 2.2 on 2019-05-29 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remision', '0008_auto_20190529_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remision',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='remision.EstadoRemision'),
        ),
    ]
