# Generated by Django 2.2 on 2019-05-29 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remision', '0009_auto_20190529_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remision',
            name='estado',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='remision.EstadoRemision'),
        ),
    ]
