# Generated by Django 2.2 on 2019-06-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remision', '0010_auto_20190529_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
