# Generated by Django 2.2 on 2019-07-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remision', '0012_auto_20190712_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medida',
            options={'verbose_name_plural': 'Unidad de Medidas'},
        ),
        migrations.AlterModelOptions(
            name='remision',
            options={'permissions': [('terminar_remision', 'Puede terminar la remision de hielo')], 'verbose_name_plural': 'Remisiones de hielo'},
        ),
    ]
