# Generated by Django 2.2 on 2019-07-24 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remision', '0013_auto_20190712_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remision',
            options={'permissions': [('terminar_remision', 'Puede terminar la remision de hielo'), ('generar_reportes', 'Puede generar reportes de remision de hielo')], 'verbose_name_plural': 'Remisiones de hielo'},
        ),
    ]
