# Generated by Django 2.2.4 on 2019-10-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remision', '0014_auto_20190723_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remision',
            name='guia',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
