# Generated by Django 2.2 on 2019-04-08 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
        ('compania', '0002_auto_20190408_1544'),
        ('conductor', '0001_initial'),
        ('empleado', '0001_initial'),
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPrestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoEquipo',
            fields=[
                ('numPrestamo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('horaSalida', models.TimeField()),
                ('fechaSalida', models.DateField()),
                ('fechaEntrada', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compania.Compania')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conductor.Conductor')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.Empleado')),
                ('estadoPrestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prestamos.EstadoPrestamo')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehiculo.Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePrestamoEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('tapadera', models.IntegerField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipo.Equipo')),
                ('prestamoEquipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.PrestamoEquipo')),
            ],
            options={
                'verbose_name_plural': 'Detalle de prestamo de equipo',
            },
        ),
    ]
