# Generated by Django 2.2 on 2019-06-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_auto_20190508_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprestamoequipo',
            name='prestamoEquipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.PrestamoEquipo'),
        ),
    ]
