# Generated by Django 2.2 on 2019-07-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_auto_20190612_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamoequipo',
            options={'permissions': [('anular_prestamoequipo', 'Puede anular prestamos de equipo'), ('terminar_prestamoequipo', 'Puede terminar prestamos de equipo'), ('imprimir_prestamoequipo', 'Puede imprimir prestamos de equipo'), ('reporte_prestamoequipo', 'Puede generar reportes de prestamos de equipo')], 'verbose_name_plural': 'Prestamo de equipos'},
        ),
    ]
