# Generated by Django 2.2.4 on 2019-09-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_auto_20190724_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprestamoequipo',
            name='devuelto',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
