# Generated by Django 2.2.4 on 2019-09-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_detalleprestamoequipo_devuelto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprestamoequipo',
            name='devuelto',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
