# Generated by Django 2.2.4 on 2019-10-09 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0008_remove_detalleprestamoequipo_tapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprestamoequipo',
            name='tapadera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tapaderas', to='equipo.Equipo'),
        ),
    ]
