# Generated by Django 2.2.4 on 2019-10-09 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0009_auto_20191009_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleprestamoequipo',
            name='tapadera',
        ),
    ]
