# Generated by Django 2.2.4 on 2019-10-10 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0006_auto_20190731_2104'),
        ('prestamos', '0010_remove_detalleprestamoequipo_tapadera'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprestamoequipo',
            name='tapadera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tapaderas', to='equipo.Equipo'),
        ),
    ]
