# Generated by Django 2.2.4 on 2019-10-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0011_detalleprestamoequipo_tapadera'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprestamoequipo',
            name='devueltoT',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
