# Generated by Django 2.2 on 2019-06-27 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleHieloProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hielo_proceso.DepartamentoProceso')),
            ],
        ),
        migrations.CreateModel(
            name='Recipiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.DecimalField(decimal_places=4, help_text='capacidad en quintales del recipiente', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='RecipienteDetalleHieloProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('detalleHieloProceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hielo_proceso.DetalleHieloProceso')),
                ('recipiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hielo_proceso.Recipiente')),
            ],
        ),
        migrations.CreateModel(
            name='HieloProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('registrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.Empleado')),
            ],
        ),
        migrations.AddField(
            model_name='detallehieloproceso',
            name='hieloProceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hielo_proceso.HieloProceso'),
        ),
    ]
