# Generated by Django 2.2 on 2019-06-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hielo_proceso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hieloproceso',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
