# Generated by Django 2.2 on 2019-06-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hielo_proceso', '0002_auto_20190627_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hieloproceso',
            name='fecha',
            field=models.DateField(),
        ),
    ]
