# Generated by Django 2.2 on 2019-06-27 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hielo_proceso', '0003_auto_20190627_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallehieloproceso',
            name='departamento',
        ),
        migrations.AddField(
            model_name='detallehieloproceso',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallehieloproceso',
            name='recipiente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hielo_proceso.Recipiente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hieloproceso',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hielo_proceso.DepartamentoProceso'),
        ),
        migrations.DeleteModel(
            name='RecipienteDetalleHieloProceso',
        ),
    ]
