# Generated by Django 2.2 on 2019-06-29 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hielo_proceso', '0005_auto_20190627_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hieloproceso',
            name='departamento',
        ),
        migrations.AddField(
            model_name='detallehieloproceso',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hielo_proceso.DepartamentoProceso'),
        ),
    ]
