# Generated by Django 2.2 on 2019-06-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hielo_proceso', '0008_auto_20190628_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallehieloproceso',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detallehieloproceso',
            name='recipiente',
        ),
        migrations.AddField(
            model_name='detallehieloproceso',
            name='bins',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Recipiente',
        ),
    ]
