# Generated by Django 2.2 on 2019-06-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hielo_proceso', '0009_auto_20190629_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallehieloproceso',
            name='carreton_blanco',
            field=models.IntegerField(default=0),
        ),
    ]
