# Generated by Django 2.2 on 2019-07-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hielo_proceso', '0011_auto_20190629_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallehieloproceso',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hielo_proceso.DepartamentoProceso'),
        ),
    ]
