# Generated by Django 2.2 on 2019-07-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hielo_proceso', '0012_auto_20190702_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hieloproceso',
            name='fecha',
            field=models.DateField(unique=True),
        ),
    ]
