# Generated by Django 2.2 on 2019-04-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=200)),
                ('abreviatura', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Compañia',
                'verbose_name_plural': 'Compañias',
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('codFinca', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compania.Compania')),
            ],
            options={
                'verbose_name_plural': 'Fincas',
            },
        ),
        migrations.CreateModel(
            name='Laguna',
            fields=[
                ('codLaguna', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tamano', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=100)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compania.Finca')),
            ],
            options={
                'verbose_name_plural': 'Lagunas',
            },
        ),
    ]
