# Generated by Django 2.2 on 2019-04-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compania', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCompania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Compañia',
                'verbose_name_plural': 'Tipos de Compañia',
            },
        ),
        migrations.RenameField(
            model_name='compania',
            old_name='Direccion',
            new_name='direccion',
        ),
        migrations.AddField(
            model_name='compania',
            name='tipoCompania',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='compania.TipoCompania'),
            preserve_default=False,
        ),
    ]
