# Generated by Django 2.2 on 2019-05-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compania', '0002_auto_20190408_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='compania',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
