# Generated by Django 2.2 on 2019-05-07 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compania', '0003_compania_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='codFinca',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo de Finca'),
        ),
        migrations.AlterField(
            model_name='finca',
            name='compania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compania.Compania', verbose_name='Empresa'),
        ),
    ]
