# Generated by Django 2.2 on 2019-08-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compania', '0004_auto_20190507_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laguna',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
