# Generated by Django 2.2 on 2019-08-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compania', '0005_auto_20190801_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compania',
            options={'permissions': [('estado_compania', 'Puede cambiar el estado de la empresa')], 'verbose_name': 'Compañia', 'verbose_name_plural': 'Compañias'},
        ),
    ]
