# Generated by Django 2.2.4 on 2019-09-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compania', '0006_auto_20190805_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compania',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='compania',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
