# Generated by Django 2.2 on 2019-07-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camaron', '0002_auto_20190707_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosecha',
            name='finca',
        ),
    ]
