# Generated by Django 2.2 on 2019-07-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camaron', '0003_remove_cosecha_finca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecosecha',
            name='cosecha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camaron.Cosecha'),
        ),
    ]
