# Generated by Django 2.2 on 2019-07-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camaron', '0004_auto_20190708_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosecha',
            options={'permissions': [('imprimir_cosecha', 'Puede imprimir las cosechas')], 'verbose_name_plural': 'Cosechas'},
        ),
    ]
