# Generated by Django 2.2.4 on 2019-10-22 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camaron', '0005_auto_20190725_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosecha',
            name='remision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cosechas', to='remision.Remision'),
        ),
    ]
