# Generated by Django 2.2 on 2019-04-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('numIdentidad', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=30)),
                ('nombre2', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido1', models.CharField(max_length=30)),
                ('apellido2', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('Celular', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Conductores',
            },
        ),
    ]
