# Generated by Django 2.2 on 2019-07-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='Celular',
            new_name='celular',
        ),
        migrations.AddField(
            model_name='conductor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
