# Generated by Django 2.2.4 on 2019-10-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0003_auto_20190805_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
