# Generated by Django 2.2 on 2019-04-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
        ('compania', '0002_auto_20190408_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(blank=True, max_length=30, null=True)),
                ('Anio', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.Color')),
                ('empresaFlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compania.Compania')),
            ],
            options={
                'verbose_name_plural': 'Vehiculos',
            },
        ),
    ]
