# Generated by Django 2.2.4 on 2019-10-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0006_auto_20190809_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
