# Generated by Django 2.2 on 2019-07-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='permisos',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tipoEmpleado',
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='TipoEmpleado',
        ),
    ]
