# Generated by Django 2.2 on 2019-07-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0007_auto_20190712_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='actualizoContrasena',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
