# Generated by Django 2.2 on 2019-07-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0011_auto_20190714_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'permissions': [('restablecer_contrasena', 'Puede restablecer la contraseña del empleado'), ('obtener_contrasena', 'Puede obtener la contraseña del empleado')], 'verbose_name_plural': 'Empleados'},
        ),
    ]
