# Generated by Django 2.2 on 2019-08-07 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0012_auto_20190715_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'permissions': [('restablecer_contrasena', 'Puede restablecer la contraseña del empleado'), ('obtener_contrasena', 'Puede obtener la contraseña del empleado'), ('estado_empleado', 'Puede cambiar el estado del empleado')], 'verbose_name_plural': 'Empleados'},
        ),
    ]
