# Generated by Django 2.2 on 2019-04-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Base de Equipo',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tamaños de los Bines',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('codigo_barras', models.CharField(blank=True, max_length=160, null=True, unique=True, verbose_name='Código de Barras')),
                ('informacion', models.TextField(blank=True, null=True)),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipo.Estado')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipo.Color')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipo.BaseEquipo')),
                ('tamano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipo.Tamano')),
            ],
            options={
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
