# Generated by Django 2.2 on 2019-04-09 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.ForeignKey(help_text='Seleccione el tipo de equipo que va a registrar', on_delete=django.db.models.deletion.PROTECT, to='equipo.BaseEquipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero',
            field=models.IntegerField(help_text='ingrese el numero unico del equipo'),
        ),
    ]
