# Generated by Django 2.2 on 2019-04-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_auto_20190409_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='Estado',
            new_name='estado',
        ),
    ]
