# Generated by Django 2.2 on 2019-05-02 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0003_auto_20190409_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='tamano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipo.Tamano', verbose_name='Tamaño'),
        ),
    ]
