# Generated by Django 2.2 on 2019-08-01 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0005_auto_20190731_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'permissions': [('crearqr_equipo', 'Puede crear codigo qr para el inventario de equipo')], 'verbose_name_plural': 'Equipos'},
        ),
    ]
